server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: resto-service
          uri: lb://resto-service
          predicates:
            - Path=/resto/**
        - id: dishes-service
          uri: lb://dishes-service
          predicates:
            - Path=/dish/**